plugins {
    id 'java-library'
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '2.0.141'
}

version = mod_version
group = mod_group_id

base {
    archivesName = mod_id + "-neoforge-" + minecraft_version
}

java.toolchain.languageVersion = JavaLanguageVersion.of(25)

sourceSets {
    main {
        resources {
            srcDir 'src/generated/client'
            srcDir 'src/generated/server'
        }
    }
}

neoForge {
    version = project.neoforge_version

    runs {
        client {
            client()
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        server {
            server()
            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        gameTestServer {
            type = "gameTestServer"
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        clientData {
            clientData()
            programArguments.addAll '--mod', project.mod_id,
                    '--output', file('src/generated/client/').getAbsolutePath(),
                    '--existing', file('src/main/resources/').getAbsolutePath(),
                    '--existing', file('src/generated/server/').getAbsolutePath()
        }

        serverData {
            serverData()
            programArguments.addAll '--mod', project.mod_id,
                    '--output', file('src/generated/server/').getAbsolutePath(),
                    '--existing', file('src/main/resources/').getAbsolutePath(),
                    '--existing', file('src/generated/client/').getAbsolutePath()
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

repositories {
    maven {
        url = "https://maven.theillusivec4.top/"
    }
    maven {
        url = "https://jitpack.io"
        content {
            includeGroup "com.github.rtyley"
        }
    }
    maven {
        name = "Jared's maven"
        url = "https://maven.blamejared.com/"
    }
    maven {
        name = "Team Resourceful Maven"
        url = "https://maven.teamresourceful.com/repository/maven-public/"
    }
    maven {
        name = "Modrinth"
        url = "https://api.modrinth.com/maven"
    }
    maven {
        url = "https://cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
    maven {
        name = "ModMaven"
        url = "https://modmaven.dev/"
    }
    maven {
        name = "RedlanceMinecraft"
        url = "https://repo.redlance.org/public"
        content {
            includeGroupByRegex "com\\.zigythebird(\\..*)?"
            includeGroupByRegex "org\\.redlance(\\..*)?"
        }
    }
    mavenCentral()
}

dependencies {
    compileOnly "mezz.jei:jei-26.1.2-neoforge-api:${jei_version}"
    runtimeOnly "mezz.jei:jei-26.1.2-neoforge:${jei_version}"

    implementation "curse.maven:hephaestus-forge-1542467:8933923"
    implementation "curse.maven:athena-841890:7970442"

    implementation "curse.maven:ftb-materials-1124942:8500413"
    implementation "curse.maven:ftb-library-forge-404465:8858835"

    implementation("com.zigythebird.playeranim:PlayerAnimationLibNeo:${pal_version}") {
        exclude group: "com.google.code.gson", module: "gson"
        exclude group: "io.netty"
        exclude group: "org.slf4j"
        exclude group: "it.unimi.dsi"
        exclude group: "org.joml"
        exclude group: "org.jetbrains", module: "annotations"
    }

}

tasks.withType(ProcessResources).configureEach {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE

    var replaceProperties = [
            minecraft_version   : minecraft_version,
            neoforge_version    : neoforge_version,
            mod_id              : mod_id,
            mod_version         : mod_version
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/neoforge.mods.toml']) {
        expand replaceProperties + [project: project]
    }
}
