org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

mod_id=hephaestus_tools
mod_version=1.0.5
mod_group_id=com.titammods

minecraft_version=26.1.2
minecraft_version_range=[26.1.1,26.1.2]
neoforge_version=26.1.2.100
jei_version=29.5.0.26
ftb-materials_version=26.1.2.5
ftb-library_version=26.1.2.8
athena_version=4.7.3
hephaestus_version=1.0.9
