modLoader="javafml"
loaderVersion="${neoforge_version}"
license="All rights reserved"
issueTrackerURL=""

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="Hephaestus Tools"
description="A modular tool mod for Hephaestus."

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neoforge_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="[26.1.1,26.1.2]"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="hephaestus"
type="required"
versionRange="[1.0.9,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="player_animation_library"
type="required"
versionRange="[1.2.0,)"
ordering="AFTER"
side="CLIENT"

[[mixins]]
config="hephaestus_tools.mixins.json"
